### ISSUE TITLE
我最近一直关注在互联网智慧系统的开源项目，请问可以合作么？

### ISSUE THREAD

**Issue by yaoguangluo** [tengge1/ShadowEditor#13]

**Comment by tengge1** [comment]
是通用人工智能(AGI)方面的项目吗？机器学习就算了。

**Comment by yaoguangluo** [comment]
我大概介绍下吧，我所理解的互联网智慧系统 包括 可重用的etl 组件节点开发技术， 简洁的socket服务器，自然语言处理，数据分析，和plsql命令行模式数据库，图片，文本，音频处理等，不知道可否合作

**Comment by tengge1** [comment]
抱歉，不感兴趣。

**Comment by yaoguangluo** [comment]
AGI可以有，把需求给我可以吗？

**Comment by tengge1** [comment]
1、通过环境训练，生命体从零开始自动创建神经网络，调整权重。
2、遗传和变异。
3、生存斗争，自然选择，适者生存。
4、不可以干预生命体，通过环境调整，积极引导生命体产生各种变异。
5、基因功能设计，给生命提供一个可以生存的最小基因组。
6、速度，提供可视化界面。

**Comment by tengge1** [comment]
正在积极筹划准备，预计一年后想明白了就可以实施。

**Comment by yaoguangluo** [comment]
你要我先写dna 遗传算法 还是做可视化界面先？

**Comment by yaoguangluo** [comment]
我有一个医学大数据的etl软件

**Comment by tengge1** [comment]
可以，拉我进去学习一下。

**Comment by yaoguangluo** [comment]
我的gitlab没有接外网，你有qq吗？我可以演示下最新的动态给你，我一般用qq工作。

**Comment by yaoguangluo** [comment]
我的是313699483

**Comment by tengge1** [comment]
我对基因怎么控制生长，不同基因之间的界限和交互倒是挺感兴趣的。

**Comment by yaoguangluo** [comment]
基因作用是一个单链， 另一根互补的是用来校验和分裂遗传的，一根单链上有功能区间，每一个区间有一个分隔密码，通过分隔密码可以截取功能区进行特定分析。
