### ISSUE TITLE
Aspect of camera is incorrect?

### ISSUE THREAD

**Issue by but0n** [tengge1/ShadowEditor#16]
![image](https://user-images.githubusercontent.com/7625588/54736472-2cf00700-4be6-11e9-8b89-a0ff59cc9a08.png)

It will be correct after manually resize the window:

![image](https://user-images.githubusercontent.com/7625588/54736520-64f74a00-4be6-11e9-87fe-7a227782da76.png)

**Comment by tengge1** [comment]
I fix this. Now `app.camera.aspect`, `app.renderer.domElement.width / app.renderer.domElement.height`, and `app.renderer.domElement.clientWidth / app.renderer.domElement.clientHeight` are both 1.7750257997936016. Thank you for your feedback.
