### ISSUE TITLE
动画无效 麻烦大佬帮忙看看哪里的问题

### ISSUE THREAD

**Issue by 240321243** [tengge1/ShadowEditor#18]
补件动画添加了 播放没有任何效果  用脚本写的动画就有效果 想问下为什么
![image](https://user-images.githubusercontent.com/48821792/54811375-85e19d00-4cc3-11e9-9e7f-70c056366f07.png)

**Comment by tengge1** [comment]
重写播放器的时候，忘记把补间动画加上了。我现在就改这个bug。

**Comment by tengge1** [comment]
bug修复好了。
