### ISSUE TITLE
使用three.js载入lol模型

### ISSUE THREAD

**Issue by 96486d9b** [tengge1/ShadowEditor#23]
您好，最近在做一个类似英雄gallery的项目，发现您已经好像继承了three.js读取lol模型的操作，基于viewer.js的，读取lmesh和lanim，我查看了这个项目，暂时没有发现这部分Js文件，请问如果可以的话，能否给出一段demo，谢谢~

**Comment by tengge1** [comment]
相关文件搜在：`https://github.com/tengge1/ShadowEditor/tree/master/ShadowEditor.Web/src/loader/lol`文件夹。

用法可用参考：`https://github.com/tengge1/ShadowEditor/blob/master/ShadowEditor.Web/src/loader/LOLLoader.js`

**Comment by 96486d9b** [comment]
您好，我看了一下，好像又引向了baseloader，请问这一块可以剥离开的吗？

**Comment by tengge1** [comment]
LOLLoader.js里关键代码是：

```javascript
var model = new LolModel({
    champion: champion,
    skin: parseInt(skin),
    meshUrl: lmesh,
    animUrl: lanim,
    textureUrl: png
});
model.load();
model.on('load.LOLLoader', () => {
    var geometry = model.geometry;
    var material = model.material;

    var mesh = new THREE.Mesh(geometry, material);
});
```

与`BaseLoader`没关系，页面需要引入`gl-matrix.js`和`pako.js`。

**Comment by 96486d9b** [comment]
嗯，是的，我刚才尝试了，已经成功了，现在就是还有一个问题，就是关于模型动画， 不太清除这个的调用方式。

**Comment by 96486d9b** [comment]
您好，已经解决了，我尝试开放了一些接口出来，再次感谢~
