### ISSUE TITLE
问下这个如何让这个轴位于几个物体的中心，而不是原点

### ISSUE THREAD

**Issue by wenrenqiang** [tengge1/ShadowEditor#25]
![image](https://user-images.githubusercontent.com/35467304/62271888-56f6e700-b46c-11e9-8f54-cd880ab0a58c.png)
不移动原始物体坐标的情况下

**Comment by wenrenqiang** [comment]
解决了

**Comment by tengge1** [comment]
你选中的是组，现在组在原点。

你选中组中的物体就好了，之间在场景中点击物体，或者点击场景树上的正方体或圆柱体。
