### ISSUE TITLE
你好可以请问一下右上角实时展示当前视图方向的图标是怎么实现的吗

### ISSUE THREAD

**Issue by DengJianShen** [tengge1/ShadowEditor#27]
感谢作者

**Comment by tengge1** [comment]
[https://github.com/tengge1/ShadowEditor/blob/master/ShadowEditor.Web/src/helper/ViewHelper.js](https://github.com/tengge1/ShadowEditor/blob/master/ShadowEditor.Web/src/helper/ViewHelper.js)
