### ISSUE TITLE
ShadowEditor  代码编辑器使用问题

### ISSUE THREAD

**Issue by langangying** [tengge1/ShadowEditor#28]
作者你好，这是我我在使用你的代码编辑器是遇到的问题。反馈如下
建议和unity 一样可以使用外部代码编辑器来解决以下吐血问题。
//代码编辑器使用问题

  1；？调试不方便，代码报错时黑屏，导致辛苦写的代码丢失，没有自动保存功能
  2；？? 写代码有保存丢失问题 /编辑器写入代码有不成功概率，改完代码还是上一次代码
  3；？？不能保存代码，丢失代码问题，  代码编辑器存在很大问题
  4；无法写代码问题，编写代码后，启用播放后任然是没有。
  5；写代码时要特别注意，不够智能
  6；报错时无法弹出代码编辑器
  7；？javaScript定时器无法结束，播放停止后还在运行
  9；注释代码目前只能单注释
  10;无法快速定位查找，替换
  11;无法保存问题, 在有代码错误情况时无法保存，但运行后错误代码直接黑屏代码直接丢失。

 代码编辑器总结???（--如果不能调用外部代码编辑器编写代码，编辑器问很难解解决---）

**Comment by langangying** [comment]
作者你好，右侧材质属性面板使用问题。反馈如下
材质设置有问题
  1； 改变材质类型后，有整个场景消失的现象
  2；obj格式模型 ，导入模型全部变成冯氏材质类型，无法手动改变材质类型。
  3;当前模型无法改变材质类型

**Comment by langangying** [comment]
作者你好，右侧属性操作面板 使用反馈如下
webGleditro 已经功能比较多，但是不好用，都是吐血问题。
  文字输入框不能右键粘贴文字，常规ctrl+c 复制变成复制模型。
右侧场景管理对象列表
  1；没有排列方式，
  2；移动对象按钮时出现整个场景管理对象列表面板一起移动（移动对象时整个UI被移动）
  2；不能多选场景对象
  3；不能修改父子级关系

**Comment by tengge1** [comment]
@langangying 好的，谢谢反馈。我会慢慢修改的。

**Comment by langangying** [comment]
谢谢！作者精神值得我学习。  我顺便更正一下
我说的代码编辑器 ，是说的脚本编辑器存在相当大的问题。不知道是否可以使用外部的编辑器来创建脚本和编写脚本解决存在问题。比如 WebStorm 之类的工具 ，应该借助外面工具 。

**Comment by tengge1** [comment]
@langangying 我记得微软那好像有web版的Visual Studio Code，我看看能不能用上。

**Comment by langangying** [comment]
作者你好！ web版的Visual Studio Code 我不了解，我想shadowEditor 创建的脚本是否可以用本地 javaScript开发工具打开去编辑，只有这样才能发挥足够强大编辑功能。 目前我用的是一个很狗血而无奈办法，脚本代码在WebStorm 编辑好后再拷贝到内部脚本编辑器运行，实在是没办法，内部脚本编辑器不适合专业开发人员正常使用。
    应该有两种方式去编辑脚本。一种是内部脚本编辑器（原来这种就行），另一种是本地javaScript开发工具打开去编辑。 多数开发人员都会把程序部署到本地。只有极少非专业开发人在远程web端访问使用，非专业内部脚本编辑也足够用。   我一直很喜欢 three.js ， 这是我的  QQ:553830270。

**Comment by tengge1** [comment]
@langangying 这可能需要做个VSCode插件。
