### ISSUE TITLE
export scene ... 

### ISSUE THREAD

**Issue by weekendkoder** [tengge1/ShadowEditor#32]
The new Version 0.54 work great ! 

This time i was able to export the published content. And this time it was inside the "temp" folder. So i could use it and upload it and so on. Next point, which is important, is to have this "export scene" or "save scene" (local). It works with "export scene". But when i export it, there is no option to import the Scene. Do you know what for the "export scene" is meant ?

As mentioned earlier, saving your own created scene localy, would be awesome. Thanks.

**Comment by tengge1** [comment]
`Export scene` means to export the whole scene to a single mesh. You can upload it in the model panel.

`Download` is not working on the electron, and I will fix this in the next version.

**Comment by weekendkoder** [comment]
Ah okay.

I recognized that we don´t have any "import" option inside the ShadowEditor. Only many export formats. I did not know exactly which format i can import (no info inside the editor). But i guessed *.fbx , *.obj , *.glTF would work, like the export options. And it worked.

With "download" you mean "saving Scene" ?
