### ISSUE TITLE
Is Video Texture example broken?

### ISSUE THREAD

**Issue by j2l** [tengge1/ShadowEditor#42]
Hello,
I'm discovering your editor on Ubuntu 20.04
Both the web and the linux app can't play the video texture, getting error:
`[17426:0515/085948.270756:ERROR:gles2_cmd_decoder.cc(10716)] [.WebGL-0x138873136700]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?`
Maybe I'm missing something?
Any idea?
Thanks

**Comment by tengge1** [comment]
Chrome support video format: mp4 h264. I think you'd better check if the video can play in a single html page.

**Comment by tengge1** [comment]
Chrome support video format: mp4 h264. I think you'd better check if the video can play in a single html page.
