### ISSUE TITLE
添加的脚本里可以用glsl吗

### ISSUE THREAD

**Issue by fenglingnan** [tengge1/ShadowEditor#46]
在右下角的添加脚本里打开新加脚本，编辑时可以用glsl吗，如果可以CodeMirror有上色吗

**Comment by tengge1** [comment]
1、脚本里使用glsl，把着色器程序字符串传给着色器材质即可。（无上色）

2、也可以把模型材质改为着色器材质，材质中可以编辑着色器程序。（有上色）

**Comment by fenglingnan** [comment]
我有试着改成create-react-app版本
![image](https://user-images.githubusercontent.com/22852520/123357955-27d84a00-d59d-11eb-9b26-332ed16c6f7f.png)
到编辑脚本这一步，请教下怎么用CodeMirror的代码提示前面加那个f，混合js和three的语法提示
看了源码是有用tern，但是cra这边不知道用tern怎么做

**Comment by tengge1** [comment]
这个不清楚，我在three.js自带编辑器基础上改的，原来就有这功能。

你可以看看tern的文档，或者使用微软开源的web编辑器：https://github.com/microsoft/monaco-editor
