### ISSUE TITLE
Linux服务器上编译失败的问题

### ISSUE THREAD

**Issue by MW8023** [tengge1/ShadowEditor#53]
大佬你好，我想问一下这个项目npm install的时候总是报错，报错内容如图所示，centos Ubuntu我都试了一样的错误
![image](https://user-images.githubusercontent.com/46080310/151497349-51d1b8b0-3299-4b23-9068-81db46e02bf7.png)
请问如何解决呢  麻烦了

**Comment by tengge1** [comment]
electron包下载失败了，先执行`npm run set-proxy`设置代理后，再执行`npm install`。

`electron`下载失败不影响使用，只是不能打包桌面版，在`package.json`中把`electron`包删除也行。

**Comment by MW8023** [comment]
> Owner

好的 谢谢  我试试
