### ISSUE TITLE
CentOS ARM64上启动报错的问题

### ISSUE THREAD

**Issue by MW8023** [tengge1/ShadowEditor#61]
大佬你好  根据你的文章提示一步一步的进行编译都是没有问题的  唯独等到npm start的时候报了这个错误  不知道啥原因
![image](https://user-images.githubusercontent.com/46080310/160348749-acefee5a-db84-44a4-9054-a9c929b95316.png)

**Comment by tengge1** [comment]
可以试试以下命令是否能启动

```sh
cd build
./ShadowEditor serve
```

如果能启动，说明问题出在nodejs上，可能是nodejs版本太高的问题
